# Generated by Django 2.1.1 on 2018-11-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('upload_csv_processed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='upload_csv.CsvUpload')),
                ('day_1', models.FloatField(blank=True, default=None, null=True)),
                ('day_2', models.FloatField(blank=True, default=None, null=True)),
                ('day_3', models.FloatField(blank=True, default=None, null=True)),
                ('day_4', models.FloatField(blank=True, default=None, null=True)),
                ('day_5', models.FloatField(blank=True, default=None, null=True)),
                ('day_6', models.FloatField(blank=True, default=None, null=True)),
                ('day_7', models.FloatField(blank=True, default=None, null=True)),
                ('image_path', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
